spring:
  datasource:
    url: jdbc:h2:tcp://127.0.0.1/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: seongilman # 3
    password: zeyfxfakdqszznjk # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

#  jpa.hibernate.ddl-auto: create